server:
  port: 9001
spring:
  application:
    name: cloud-consumer-order1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
  instance:
    instance-id: cloud-consumer-order1
    # 访问路径可以显示ip地址
    prefer-ip-address: true