server:
  # 8002表示注册到zookeeper服务器的支付服务提供者端口号
  port: 8002
spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-provider-payment2
  cloud:
    zookeeper:
      # 默认localhost:2181
      connect-string: 172.20.1.151:2181