server:
  port: 9001
spring:
  application:
    name: cloud-consumer-order1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    defaultZone: http://172.20.1.151:8001/eureka
  instance:
    instance-id: cloud-consumer-order1
    # 访问路径可以显示ip地址
    prefer-ip-address: true