server:
  port: 8001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 118.24.198.239:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'